### ISSUE TITLE
Need an explicit error when the creation of a device fails with the return JSON of the error

### ISSUE THREAD

**Issue by mansona** [serverdensity/chef-serverdensity#16]
We use a test box that always has the same hostname to test our server deployments, when we were trying to get server density installed we kept getting the following error: 
```
#<NoMethodError: undefined method `response' for #<NameError:0x00000004227b68>>
       [2015-01-23T10:36:01+00:00] WARN: Unable to create device on Serverdensity
```
I was on with support and they said that this is most likely because the same key exists in the account and that would be stated in the return JSON. 

If we could just print out the return JSON when there is an error that would be really useful and would have allowed us to figure out this problem much earlier.

**Comment by digilist** [comment]
I am getting the same error, but in my case there is no request sent at all. I think the "undefined message response" error is responsible for that. By debugging this issue, I got the error message "uninitialized constant ServerDensity::API::Base::RestClient` (which is catched in the rescue block after sending the request. Then, there is a call to "err.response" which does not exist on the provided exception.

Unfortunately, I am not sure how to fix this. It would be great if someone could look into this issue.

**Comment by shurl** [comment]
We've released v3 of the cookbook, if you still deem this an issue please get in touch.
