### ISSUE TITLE
Unable to acquire a ServerDensity agent_key

### ISSUE THREAD

**Issue by shanethehat** [serverdensity/chef-serverdensity#23]
I have recently started getting the error "RuntimeError: Unable to acquire a ServerDensity agent_key" on a server that has previously installed the agent successfully. The agent is still reporting and monitoring data is coming in, but I am unable to reprovision the server. Any ideas what I can do to debug this?

**Comment by harryperks** [comment]
Hi Shane. We've seen this before and it's related to a depreciated gem being used which has been fixed in 2.1.1. Can you update and confirm it works properly?

**Comment by benr** [comment]
I'm running 2.1.3 and having this problem.

**Comment by harryperks** [comment]
ZD ref 7712

**Comment by harryperks** [comment]
.create method of RestClient::Response now takes 4 arguments (3 args below 1.8.0)

http://www.rubydoc.info/gems/rest-client/1.8.0/RestClient/Response
http://www.rubydoc.info/gems/rest-client/1.6.1/RestClient/Response

We'll need to publish an updated cookbook.

**Comment by harryperks** [comment]
This has been resolved in 2.1.4 which has been published (https://supermarket.chef.io/cookbooks/serverdensity)
